# Generated by Django 3.2.5 on 2021-08-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0003_auto_20210805_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='magazin'),
        ),
    ]
